# Generated by Django 4.2.1 on 2023-06-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
