# Generated by Django 4.2.1 on 2023-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_is_booked_alter_hotel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=True, verbose_name='Is Booked'),
        ),
    ]
