# Generated by Django 4.2.1 on 2023-06-27 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0004_room_image_alter_room_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='media/room_photos/default.jpg', null=True, upload_to='media/room_photos/', verbose_name='Room Image'),
        ),
    ]
