# Generated by Django 4.2.1 on 2023-06-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_room_user_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='User',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
