# Generated by Django 4.2.1 on 2023-06-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/', verbose_name='Room Image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is Booked'),
        ),
    ]
