# Generated by Django 4.2.1 on 2023-06-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='middle_star',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
