# Generated by Django 4.2.1 on 2023-06-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_middle_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='middle_star',
        ),
    ]
